version: "3.8"

services:
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "80:80"

  backend:
    build: ./backend
    ports:
      - "5000:5000"

  nginx:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
